---
swagger: '2.0'
info:
  version: 1.0.0
  title: user api
  description: |
    #### User register and login api
schemes:
  - http
host: 127.0.0.1
basePath: /v1
paths:
  /train:
    get:
      responses:
        200:
          description: train
    post:
      responses:
        200:
          description: train
      parameters:
        - name: userName
          in: formData
          description: user name
          type: string
        - name: dataset
          in: formData
          description: data set of user
          type: array
          items:
            type: array
            items:
                type: string
  /predict:
    get:
      responses:
        200:
          description: predict
  
      parameters:
        - name: userName
          in: formData
          description: user name
          type: string
        - name: dataset
          in: formData
          description: data set of user
          type: array
          items:
            type: array
            items:
                type: string
 